# Generated by Django 5.2.7 on 2025-11-05 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=200)),
                ('fecha', models.DateField()),
                ('horas_trabajadas', models.CharField(max_length=50)),
                ('mes', models.CharField(max_length=20)),
                ('empresa', models.CharField(choices=[('VERFRUT', 'VERFRUT'), ('RAPEL', 'RAPEL')], max_length=20)),
            ],
            options={
                'ordering': ['-fecha'],
                'unique_together': {('dni', 'fecha', 'empresa')},
            },
        ),
    ]
